parameters:
    mailer_signatory: '%env(MAILER_SIGNATORY)%'
    mailer_sender_address: '%env(MAILER_SENDER_ADDRESS)%'
    mailer_sender_name: '%env(MAILER_SENDER_NAME)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Schvoy\MailTemplateBundle\:
        resource: '../../../src/*'
        exclude:
            - '../../../src/{DependencyInjection,Exceptions,Resources}'

    Schvoy\MailTemplateBundle\Mailer\MailSender:
        public: true